CREATE USER "testtask" PASSWORD 'testtask' ADMIN;

CREATE TABLE PATIENT
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    surname      VARCHAR(255) NOT NULL,
    name         VARCHAR(255) NOT NULL,
    second_name  VARCHAR(255) NOT NULL,
    phone_number VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)

);

CREATE TABLE DOCTOR
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    name            VARCHAR(255) NOT NULL,
    surname         VARCHAR(255) NOT NULL,
    second_name     VARCHAR(255) NOT NULL,
    specialization  VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)

);

CREATE TABLE RECIPE
(
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    description                 VARCHAR(255),
    created_date                VARCHAR(10),
    validity                    INT,
    priority                    VARCHAR(10) NOT NULL,
    patient_id                  BIGINT NOT NULL,
    doctor_id                   BIGINT NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (patient_id)    REFERENCES PATIENT,
    FOREIGN KEY (doctor_id)     REFERENCES DOCTOR
);